/**
 * Goal templates API route.
 *
 * GET /api/goal-templates - List all available goal templates
 *
 * Returns predefined goal templates that can be used to create client goals.
 * Templates define the metric type, default targets, and computation methods.
 */
import { NextResponse } from "next/server";
import { requireAuth, AuthError } from "@/lib/auth/api-auth";
import { getFastApi, FastApiError } from "@/lib/server-fetch";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Goal template structure matching the frontend interface.
 */
interface GoalTemplate {
  id: string;
  goalType: string;
  name: string;
  description: string | null;
  unit: string | null;
  defaultTarget: string | null;
  hasDenominator: boolean;
  computationMethod: string;
  isActive: boolean;
  displayOrder: number;
  createdAt: string;
}

interface TemplatesResponse {
  templates: GoalTemplate[];
}

/**
 * Default goal templates when backend doesn't have a templates endpoint.
 *
 * These match the synthetic goals generated by the FastAPI backend
 * and provide common SEO/marketing goal types.
 */
const DEFAULT_TEMPLATES: GoalTemplate[] = [
  {
    id: "tpl-traffic",
    goalType: "traffic",
    name: "Increase Organic Traffic",
    description: "Grow organic search clicks by a target percentage",
    unit: "clicks",
    defaultTarget: "1000",
    hasDenominator: false,
    computationMethod: "sum",
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-rankings",
    goalType: "rankings",
    name: "Improve Average Position",
    description: "Improve average search position to target value",
    unit: "position",
    defaultTarget: "10",
    hasDenominator: false,
    computationMethod: "average",
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-impressions",
    goalType: "visibility",
    name: "Increase Search Impressions",
    description: "Grow total search impressions",
    unit: "impressions",
    defaultTarget: "10000",
    hasDenominator: false,
    computationMethod: "sum",
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-ctr",
    goalType: "engagement",
    name: "Improve Click-Through Rate",
    description: "Increase CTR from search results",
    unit: "%",
    defaultTarget: "5",
    hasDenominator: false,
    computationMethod: "ratio",
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-keywords",
    goalType: "keywords",
    name: "Ranking Keywords",
    description: "Number of keywords ranking in top positions",
    unit: "keywords",
    defaultTarget: "50",
    hasDenominator: false,
    computationMethod: "count",
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-backlinks",
    goalType: "authority",
    name: "Build Backlinks",
    description: "Acquire high-quality backlinks",
    unit: "links",
    defaultTarget: "25",
    hasDenominator: false,
    computationMethod: "count",
    isActive: true,
    displayOrder: 6,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-sessions",
    goalType: "traffic",
    name: "Organic Sessions",
    description: "Increase organic sessions from GA4",
    unit: "sessions",
    defaultTarget: "5000",
    hasDenominator: false,
    computationMethod: "sum",
    isActive: true,
    displayOrder: 7,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tpl-conversions",
    goalType: "conversions",
    name: "Organic Conversions",
    description: "Conversions from organic traffic",
    unit: "conversions",
    defaultTarget: "100",
    hasDenominator: false,
    computationMethod: "sum",
    isActive: true,
    displayOrder: 8,
    createdAt: new Date().toISOString(),
  },
];

export async function GET() {
  try {
    await requireAuth();

    // Try to fetch templates from backend first
    try {
      const data = await getFastApi<TemplatesResponse>("/api/goal-templates");
      return NextResponse.json(data);
    } catch (backendErr) {
      // If backend doesn't have templates endpoint (404), use defaults
      if (backendErr instanceof FastApiError && backendErr.status === 404) {
        return NextResponse.json({ templates: DEFAULT_TEMPLATES });
      }
      throw backendErr;
    }
  } catch (err) {
    if (err instanceof AuthError) {
      return NextResponse.json({ error: err.message }, { status: err.statusCode });
    }
    if (err instanceof FastApiError) {
      return NextResponse.json(err.sanitizedBody, { status: err.status });
    }
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}
