/**
 * ContentGroupCard
 * Phase 96-04: Content Group display with metrics
 * WCAG 2.1 AA compliant: focus indicators, aria-labels, keyboard navigation
 */
import { Folder, Hash, Settings, Trash2, TrendingUp, TrendingDown } from "lucide-react";
import type { ContentGroupWithMetrics } from "@/server/features/analytics/types";

interface ContentGroupCardProps {
  group: ContentGroupWithMetrics;
  onEdit?: (group: ContentGroupWithMetrics) => void;
  onDelete?: (group: ContentGroupWithMetrics) => void;
  onClick?: (group: ContentGroupWithMetrics) => void;
}

export function ContentGroupCard({
  group,
  onEdit,
  onDelete,
  onClick,
}: ContentGroupCardProps) {
  const formatNumber = (n: number) => {
    if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
    if (n >= 1000) return `${(n / 1000).toFixed(1)}K`;
    return n.toString();
  };

  const getMatchTypeIcon = () => {
    switch (group.matchType) {
      case "folder":
        return <Folder className="h-4 w-4" aria-hidden="true" />;
      case "regex":
        return <Hash className="h-4 w-4" aria-hidden="true" />;
      default:
        return <Settings className="h-4 w-4" aria-hidden="true" />;
    }
  };

  const getTrendIcon = (change: number) => {
    if (change > 0) return <TrendingUp className="h-3 w-3 text-green-500" aria-hidden="true" />;
    if (change < 0) return <TrendingDown className="h-3 w-3 text-red-500" aria-hidden="true" />;
    return null;
  };

  // Generate accessible description for the card
  const cardAriaLabel = `Content group: ${group.name}. ${formatNumber(group.metrics.totalClicks)} clicks${group.metrics.clicksChange !== 0 ? ` (${group.metrics.clicksChange > 0 ? '+' : ''}${group.metrics.clicksChange.toFixed(1)}%)` : ''}, ${formatNumber(group.metrics.totalImpressions)} impressions, average position ${group.metrics.avgPosition.toFixed(1)}, ${group.pageCount} pages.${group.isAutoGenerated ? ' Auto-generated group.' : ''}`;

  return (
    <div
      className="group relative rounded-xl bg-[var(--surface)] p-4 shadow-[var(--shadow-card)] transition-all hover:shadow-[var(--shadow-lift)] hover:-translate-y-px dark:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2"
      onClick={() => onClick?.(group)}
      onKeyDown={(e) => {
        if (onClick && (e.key === "Enter" || e.key === " ")) {
          e.preventDefault();
          onClick(group);
        }
      }}
      role={onClick ? "button" : "article"}
      tabIndex={onClick ? 0 : undefined}
      aria-label={cardAriaLabel}
    >
      {/* Header */}
      <div className="mb-3 flex items-start justify-between">
        <div className="flex items-center gap-2">
          <div
            className="flex h-8 w-8 items-center justify-center rounded-md"
            style={{ backgroundColor: group.color || "#6366f1" }}
          >
            <span className="text-white">{getMatchTypeIcon()}</span>
          </div>
          <div>
            <h3 className="font-medium text-gray-900 dark:text-white">
              {group.name}
            </h3>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              {group.matchPattern || "Manual selection"}
            </p>
          </div>
        </div>
        <div className="flex gap-1 opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100">
          {onEdit && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onEdit(group);
              }}
              aria-label={`Edit content group: ${group.name}`}
              className="rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-gray-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2"
            >
              <Settings className="h-4 w-4" aria-hidden="true" />
            </button>
          )}
          {onDelete && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onDelete(group);
              }}
              aria-label={`Delete content group: ${group.name}`}
              className="rounded p-1 text-gray-400 hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-900/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500 focus-visible:ring-offset-2"
            >
              <Trash2 className="h-4 w-4" aria-hidden="true" />
            </button>
          )}
        </div>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-2 gap-3">
        <div className="rounded-md bg-gray-50 p-2 dark:bg-gray-700/50">
          <p className="text-xs text-gray-500 dark:text-gray-400">Clicks</p>
          <div className="flex items-center gap-1">
            <p className="text-lg font-semibold text-gray-900 dark:text-white">
              {formatNumber(group.metrics.totalClicks)}
            </p>
            {getTrendIcon(group.metrics.clicksChange)}
            {group.metrics.clicksChange !== 0 && (
              <span
                className={`text-xs ${
                  group.metrics.clicksChange > 0
                    ? "text-green-600"
                    : "text-red-600"
                }`}
              >
                {group.metrics.clicksChange > 0 ? "+" : ""}
                {group.metrics.clicksChange.toFixed(1)}%
              </span>
            )}
          </div>
        </div>

        <div className="rounded-md bg-gray-50 p-2 dark:bg-gray-700/50">
          <p className="text-xs text-gray-500 dark:text-gray-400">Impressions</p>
          <div className="flex items-center gap-1">
            <p className="text-lg font-semibold text-gray-900 dark:text-white">
              {formatNumber(group.metrics.totalImpressions)}
            </p>
            {getTrendIcon(group.metrics.impressionsChange)}
          </div>
        </div>

        <div className="rounded-md bg-gray-50 p-2 dark:bg-gray-700/50">
          <p className="text-xs text-gray-500 dark:text-gray-400">Avg Position</p>
          <p className="text-lg font-semibold text-gray-900 dark:text-white">
            {group.metrics.avgPosition.toFixed(1)}
          </p>
        </div>

        <div className="rounded-md bg-gray-50 p-2 dark:bg-gray-700/50">
          <p className="text-xs text-gray-500 dark:text-gray-400">Pages</p>
          <p className="text-lg font-semibold text-gray-900 dark:text-white">
            {group.pageCount}
          </p>
        </div>
      </div>

      {/* Auto-generated badge */}
      {group.isAutoGenerated && (
        <div className="mt-2 flex justify-end">
          <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
            Auto-generated
          </span>
        </div>
      )}
    </div>
  );
}
