/**
 * ContentGroupService
 * Phase 96-04: Content Groups with Auto-Grouping
 *
 * Handles business logic for content groups including:
 * - Auto-generation from folder patterns
 * - Regex and folder-based matching
 * - Manual page additions
 * - Metrics aggregation from GSC data
 */
import { ContentGroupRepository } from "../repositories/ContentGroupRepository";
import type {
  ContentGroupWithMetrics,
  ContentGroupCreateInput,
  ContentGroupUpdateInput,
  AutoGroupResult,
} from "../types";

export class ContentGroupService {
  private repo: ContentGroupRepository;

  constructor() {
    this.repo = new ContentGroupRepository();
  }

  /**
   * Auto-generate content groups from detected folder patterns
   * Looks for patterns like /blog/, /products/, /services/ with >= 3 pages
   */
  async autoGenerateGroups(siteId: string): Promise<AutoGroupResult> {
    const folders = await this.repo.getDistinctFolders(siteId, 3);
    const existingGroups = await this.repo.findBySiteId(siteId);

    const existingPatterns = new Set(
      existingGroups
        .filter((g) => g.matchType === "folder")
        .map((g) => g.matchPattern)
    );

    const created: ContentGroupWithMetrics[] = [];
    const skipped: Array<{ folder: string; reason: string; pageCount: number }> = [];

    for (const folder of folders) {
      // Skip if a group with this pattern already exists
      if (existingPatterns.has(folder.folder)) {
        skipped.push({
          folder: folder.folder,
          reason: "Group already exists",
          pageCount: folder.pageCount,
        });
        continue;
      }

      // Generate a nice name from the folder
      const name = this.folderToName(folder.folder);

      // Create the group
      const group = await this.repo.create({
        siteId,
        name,
        matchType: "folder",
        matchPattern: folder.folder,
        isAutoGenerated: true,
      });

      // Populate pages matching the pattern
      await this.populateGroupPages(group.id, siteId, "folder", folder.folder);

      // Get metrics for the group
      const withMetrics = await this.getGroupWithMetrics(group.id, siteId);
      if (withMetrics) {
        created.push(withMetrics);
      }
    }

    return { created, skipped };
  }

  /**
   * Create a new content group
   */
  async createGroup(
    siteId: string,
    input: ContentGroupCreateInput
  ): Promise<ContentGroupWithMetrics | null> {
    const group = await this.repo.create({
      siteId,
      name: input.name,
      description: input.description,
      matchType: input.matchType,
      matchPattern: input.matchPattern,
      color: input.color,
      isAutoGenerated: false,
    });

    // Auto-populate pages if we have a pattern
    if (input.matchType !== "manual" && input.matchPattern) {
      await this.populateGroupPages(
        group.id,
        siteId,
        input.matchType,
        input.matchPattern
      );
    }

    return this.getGroupWithMetrics(group.id, siteId);
  }

  /**
   * Get all groups for a site with metrics
   */
  async getGroups(siteId: string): Promise<ContentGroupWithMetrics[]> {
    const groups = await this.repo.findBySiteId(siteId);
    const results: ContentGroupWithMetrics[] = [];

    for (const group of groups) {
      const withMetrics = await this.getGroupWithMetrics(group.id, siteId);
      if (withMetrics) {
        results.push(withMetrics);
      }
    }

    return results;
  }

  /**
   * Get a single group with metrics
   */
  async getGroupWithMetrics(
    groupId: string,
    siteId: string
  ): Promise<ContentGroupWithMetrics | null> {
    const group = await this.repo.findById(groupId);
    if (!group) return null;

    const pages = await this.repo.getGroupPages(groupId);
    const pageUrls = pages.map((p) => p.pageUrl);

    // Calculate date ranges (last 28 days vs previous 28 days)
    const now = new Date();
    const currentEnd = now.toISOString().split("T")[0];
    const currentStart = new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0];
    const prevEnd = new Date(now.getTime() - 29 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0];
    const prevStart = new Date(now.getTime() - 57 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0];

    const metrics = await this.repo.getGroupMetrics(
      pageUrls,
      siteId,
      currentStart,
      currentEnd,
      prevStart,
      prevEnd
    );

    const clicksChange =
      metrics.prevClicks > 0
        ? ((metrics.totalClicks - metrics.prevClicks) / metrics.prevClicks) * 100
        : 0;

    const impressionsChange =
      metrics.prevImpressions > 0
        ? ((metrics.totalImpressions - metrics.prevImpressions) /
            metrics.prevImpressions) *
          100
        : 0;

    return {
      id: group.id,
      siteId: group.siteId,
      name: group.name,
      description: group.description,
      matchType: group.matchType as "folder" | "regex" | "manual",
      matchPattern: group.matchPattern,
      color: group.color,
      isAutoGenerated: group.isAutoGenerated,
      pageCount: pageUrls.length,
      metrics: {
        totalClicks: metrics.totalClicks,
        totalImpressions: metrics.totalImpressions,
        avgPosition: metrics.avgPosition,
        clicksChange,
        impressionsChange,
      },
      createdAt: group.createdAt,
      updatedAt: group.updatedAt,
    };
  }

  /**
   * Update a content group
   */
  async updateGroup(
    groupId: string,
    siteId: string,
    input: ContentGroupUpdateInput
  ): Promise<ContentGroupWithMetrics | null> {
    const existing = await this.repo.findById(groupId);
    if (!existing) return null;

    // Update the group
    await this.repo.update(groupId, {
      name: input.name,
      description: input.description,
      matchPattern: input.matchPattern,
      color: input.color,
    });

    // Re-populate pages if pattern changed
    if (input.matchPattern && input.matchPattern !== existing.matchPattern) {
      await this.populateGroupPages(
        groupId,
        siteId,
        existing.matchType as "folder" | "regex" | "manual",
        input.matchPattern
      );
    }

    return this.getGroupWithMetrics(groupId, siteId);
  }

  /**
   * Delete a content group
   */
  async deleteGroup(groupId: string): Promise<boolean> {
    return this.repo.delete(groupId);
  }

  /**
   * Add a page manually to a group
   */
  async addPageToGroup(groupId: string, pageUrl: string): Promise<void> {
    await this.repo.addPageToGroup(groupId, pageUrl, true);
  }

  /**
   * Remove a page from a group
   */
  async removePageFromGroup(groupId: string, pageUrl: string): Promise<void> {
    await this.repo.removePageFromGroup(groupId, pageUrl);
  }

  /**
   * Populate group pages based on match type and pattern
   */
  private async populateGroupPages(
    groupId: string,
    siteId: string,
    matchType: "folder" | "regex" | "manual",
    matchPattern: string
  ): Promise<void> {
    // Clear existing auto-added pages
    await this.repo.clearGroupPages(groupId, true);

    let pageUrls: string[] = [];

    if (matchType === "folder") {
      pageUrls = await this.repo.getPagesMatchingFolder(siteId, matchPattern);
    } else if (matchType === "regex") {
      pageUrls = await this.repo.getPagesMatchingRegex(siteId, matchPattern);
    }

    // Add matching pages
    for (const pageUrl of pageUrls) {
      await this.repo.addPageToGroup(groupId, pageUrl, false);
    }
  }

  /**
   * Convert folder path to a nice display name
   * e.g., "/blog/" -> "Blog", "/products/shoes/" -> "Products Shoes"
   */
  private folderToName(folder: string): string {
    return folder
      .split("/")
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
      .join(" ");
  }
}
