/**
 * AnnotationsRepository
 * Phase 96-03: Annotation storage and retrieval
 */
import { eq, and, gte, lte, inArray, or, isNull } from 'drizzle-orm';
import { type DbClient } from '@/db';
import { annotations } from '@/db/content-intelligence-schema';
import type { Annotation, AnnotationFilters, AnnotationType } from '../types';

export class AnnotationsRepository {
  constructor(private db: DbClient) {}

  /**
   * Get annotations for a site/workspace with filters.
   */
  async findByFilters(workspaceId: string, filters: AnnotationFilters = {}): Promise<Annotation[]> {
    const conditions = [eq(annotations.workspaceId, workspaceId)];

    if (filters.siteId) {
      if (filters.includeGlobal) {
        conditions.push(or(
          eq(annotations.siteId, filters.siteId),
          isNull(annotations.siteId)
        )!);
      } else {
        conditions.push(eq(annotations.siteId, filters.siteId));
      }
    }

    if (filters.startDate) {
      conditions.push(gte(annotations.annotationDate, filters.startDate));
    }

    if (filters.endDate) {
      conditions.push(lte(annotations.annotationDate, filters.endDate));
    }

    if (filters.types?.length) {
      conditions.push(inArray(annotations.annotationType, filters.types));
    }

    const results = await this.db
      .select()
      .from(annotations)
      .where(and(...conditions))
      .orderBy(annotations.annotationDate);

    return results as unknown as Annotation[];
  }

  /**
   * Upsert Google algorithm update annotation.
   */
  async upsertGoogleUpdate(
    workspaceId: string,
    update: {
      date: Date;
      name: string;
      description?: string;
      type: AnnotationType;
      sourceUrl?: string;
    }
  ): Promise<void> {
    await this.db
      .insert(annotations)
      .values({
        id: crypto.randomUUID(),
        siteId: null, // Global annotation
        workspaceId,
        annotationDate: update.date.toISOString().split('T')[0], // Convert to date string
        annotationType: update.type,
        title: update.name,
        description: update.description,
        impact: 'unknown',
        autoGenerated: true,
        sourceUrl: update.sourceUrl,
      })
      .onConflictDoUpdate({
        target: [annotations.workspaceId, annotations.annotationDate, annotations.title],
        set: {
          description: update.description,
          sourceUrl: update.sourceUrl,
        },
      });
  }

  /**
   * Create custom annotation.
   */
  async createCustom(
    workspaceId: string,
    siteId: string,
    data: {
      date: Date;
      title: string;
      description?: string;
      impact: 'positive' | 'negative' | 'neutral';
      createdBy: string;
    }
  ): Promise<Annotation> {
    const [annotation] = await this.db
      .insert(annotations)
      .values({
        id: crypto.randomUUID(),
        siteId,
        workspaceId,
        annotationDate: data.date.toISOString().split('T')[0], // Convert to date string
        annotationType: 'custom',
        title: data.title,
        description: data.description,
        impact: data.impact,
        autoGenerated: false,
        createdBy: data.createdBy,
      })
      .returning();

    return annotation as unknown as Annotation;
  }

  /**
   * Delete annotation.
   */
  async delete(id: string, workspaceId: string): Promise<void> {
    await this.db
      .delete(annotations)
      .where(and(
        eq(annotations.id, id),
        eq(annotations.workspaceId, workspaceId)
      ));
  }
}
