/**
 * AnnotationsRepository Tests
 * Phase 96-03: Annotation storage and retrieval
 *
 * RED Phase: Write tests first - they should FAIL
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { AnnotationFilters, AnnotationType } from '../types';

// Mock the database module
vi.mock('@/db', () => ({
  db: {
    select: vi.fn(() => ({
      from: vi.fn(() => ({
        where: vi.fn(() => ({
          orderBy: vi.fn(() => Promise.resolve([])),
        })),
      })),
    })),
    insert: vi.fn(() => ({
      values: vi.fn(() => ({
        onConflictDoUpdate: vi.fn(() => Promise.resolve()),
        returning: vi.fn(() => Promise.resolve([{ id: 'test-id' }])),
      })),
    })),
    delete: vi.fn(() => ({
      where: vi.fn(() => Promise.resolve()),
    })),
  },
}));

vi.mock('@/db/analytics-schema', () => ({
  annotations: {
    workspaceId: 'workspaceId',
    siteId: 'siteId',
    annotationDate: 'annotationDate',
    annotationType: 'annotationType',
    id: 'id',
  },
}));

// Now import after mocking
const { AnnotationsRepository } = await import('./AnnotationsRepository');
const { db: mockDb } = await import('@/db');

describe('AnnotationsRepository', () => {
  let repository: AnnotationsRepository;
  const mockWorkspaceId = 'workspace-123';
  const mockSiteId = 'site-123';

  beforeEach(() => {
    vi.clearAllMocks();
    repository = new AnnotationsRepository(mockDb as any);
  });

  describe('findByFilters', () => {
    it('should fetch annotations for a workspace', async () => {
      const mockAnnotations = [
        {
          id: 'ann-1',
          workspaceId: mockWorkspaceId,
          siteId: null,
          annotationDate: new Date('2024-03-15'),
          annotationType: 'core_update',
          title: 'March 2024 Core Update',
          impact: 'unknown',
          autoGenerated: true,
        },
      ];

      // Mock the query chain
      const mockOrderBy = vi.fn(() => Promise.resolve(mockAnnotations));
      const mockWhere = vi.fn(() => ({ orderBy: mockOrderBy }));
      const mockFrom = vi.fn(() => ({ where: mockWhere }));
      (mockDb.select as any).mockReturnValue({ from: mockFrom });

      const result = await repository.findByFilters(mockWorkspaceId, {});

      expect(result).toEqual(mockAnnotations);
      expect(mockDb.select).toHaveBeenCalled();
    });

    it('should filter by siteId when provided', async () => {
      const mockOrderBy = vi.fn(() => Promise.resolve([]));
      const mockWhere = vi.fn(() => ({ orderBy: mockOrderBy }));
      const mockFrom = vi.fn(() => ({ where: mockWhere }));
      (mockDb.select as any).mockReturnValue({ from: mockFrom });

      await repository.findByFilters(mockWorkspaceId, { siteId: mockSiteId });

      expect(mockDb.select).toHaveBeenCalled();
    });

    it('should include global annotations when includeGlobal is true', async () => {
      const mockOrderBy = vi.fn(() => Promise.resolve([]));
      const mockWhere = vi.fn(() => ({ orderBy: mockOrderBy }));
      const mockFrom = vi.fn(() => ({ where: mockWhere }));
      (mockDb.select as any).mockReturnValue({ from: mockFrom });

      await repository.findByFilters(mockWorkspaceId, {
        siteId: mockSiteId,
        includeGlobal: true,
      });

      expect(mockDb.select).toHaveBeenCalled();
    });
  });

  describe('upsertGoogleUpdate', () => {
    it('should insert new Google algorithm update', async () => {
      const mockReturning = vi.fn(() => Promise.resolve());
      const mockOnConflict = vi.fn(() => ({ returning: mockReturning }));
      const mockValues = vi.fn(() => ({ onConflictDoUpdate: mockOnConflict }));
      (mockDb.insert as any).mockReturnValue({ values: mockValues });

      await repository.upsertGoogleUpdate(mockWorkspaceId, {
        date: new Date('2024-03-15'),
        name: 'March 2024 Core Update',
        description: 'A significant core algorithm update',
        type: 'core_update' as AnnotationType,
        sourceUrl: 'https://example.com',
      });

      expect(mockDb.insert).toHaveBeenCalled();
      expect(mockValues).toHaveBeenCalled();
    });

    it('should update existing annotation on conflict', async () => {
      const mockReturning = vi.fn(() => Promise.resolve());
      const mockOnConflict = vi.fn(() => ({ returning: mockReturning }));
      const mockValues = vi.fn(() => ({ onConflictDoUpdate: mockOnConflict }));
      (mockDb.insert as any).mockReturnValue({ values: mockValues });

      await repository.upsertGoogleUpdate(mockWorkspaceId, {
        date: new Date('2024-03-15'),
        name: 'March 2024 Core Update',
        type: 'core_update' as AnnotationType,
      });

      expect(mockOnConflict).toHaveBeenCalled();
    });
  });

  describe('createCustom', () => {
    it('should create custom annotation', async () => {
      const mockAnnotation = {
        id: 'custom-ann-1',
        siteId: mockSiteId,
        workspaceId: mockWorkspaceId,
        annotationDate: new Date('2024-03-20'),
        annotationType: 'custom',
        title: 'Website Redesign',
        description: 'Launched new homepage design',
        impact: 'positive',
        autoGenerated: false,
        createdBy: 'user-123',
        createdAt: new Date(),
      };

      const mockReturning = vi.fn(() => Promise.resolve([mockAnnotation]));
      const mockValues = vi.fn(() => ({ returning: mockReturning }));
      (mockDb.insert as any).mockReturnValue({ values: mockValues });

      const result = await repository.createCustom(
        mockWorkspaceId,
        mockSiteId,
        {
          date: new Date('2024-03-20'),
          title: 'Website Redesign',
          description: 'Launched new homepage design',
          impact: 'positive',
          createdBy: 'user-123',
        }
      );

      expect(result).toEqual(mockAnnotation);
      expect(mockDb.insert).toHaveBeenCalled();
    });
  });

  describe('delete', () => {
    it('should delete annotation by id and workspace', async () => {
      const mockWhere = vi.fn(() => Promise.resolve());
      (mockDb.delete as any).mockReturnValue({ where: mockWhere });

      await repository.delete('ann-1', mockWorkspaceId);

      expect(mockDb.delete).toHaveBeenCalled();
      expect(mockWhere).toHaveBeenCalled();
    });
  });
});
