"use client";

import { useState, useCallback } from "react";
import {
  Button,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  Checkbox,
  Label,
  Input,
} from "@tevero/ui";
import { FileSpreadsheet, FileText } from "lucide-react";
import type { ExportColumn, ClientMetrics } from "@/lib/dashboard/types";
import { EXPORT_COLUMN_LABELS } from "@/lib/dashboard/types";
import { generateCSV, type CSVColumn } from "@/lib/export/csv";
import { generatePDF, type PDFColumn, createPDFOptions } from "@/lib/export/pdf";

export type ExportFormat = "csv" | "pdf";

const ALL_COLUMNS: ExportColumn[] = [
  "clientName",
  "healthScore",
  "trafficCurrent",
  "trafficTrendPct",
  "keywordsTotal",
  "keywordsTop10",
  "keywordsTop3",
  "keywordsPosition1",
  "alertsOpen",
  "connectionStatus",
  "lastReportAt",
  "lastAuditAt",
];

const DEFAULT_COLUMNS: ExportColumn[] = [
  "clientName",
  "healthScore",
  "trafficCurrent",
  "trafficTrendPct",
  "keywordsTotal",
  "alertsOpen",
];

interface ExportDialogProps {
  /** Whether the dialog is open */
  open: boolean;
  /** Callback when dialog open state changes */
  onOpenChange: (open: boolean) => void;
  /** Export format (CSV or PDF) */
  format: ExportFormat;
  /** Optional: change format within dialog */
  onFormatChange?: (format: ExportFormat) => void;
  /** Optional: pre-filtered data to export. If not provided, fetches from API. */
  data?: ClientMetrics[];
  /** Optional: custom title for the export */
  title?: string;
  /** Optional: callback when export is complete */
  onExportComplete?: () => void;
}

export function ExportDialog({
  open,
  onOpenChange,
  format,
  onFormatChange,
  data,
  title = "Client Portfolio Report",
  onExportComplete,
}: ExportDialogProps) {
  const [selectedColumns, setSelectedColumns] = useState<ExportColumn[]>(DEFAULT_COLUMNS);
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>(format);
  const [filename, setFilename] = useState(
    `clients-export-${new Date().toISOString().split("T")[0]}`
  );
  const [isExporting, setIsExporting] = useState(false);

  // Sync format when prop changes
  if (format !== selectedFormat && open) {
    setSelectedFormat(format);
  }

  const toggleColumn = (column: ExportColumn) => {
    setSelectedColumns((prev) =>
      prev.includes(column)
        ? prev.filter((c) => c !== column)
        : [...prev, column]
    );
  };

  const handleFormatChange = (newFormat: ExportFormat) => {
    setSelectedFormat(newFormat);
    onFormatChange?.(newFormat);
  };

  const buildColumns = useCallback(() => {
    return selectedColumns.map((col) => ({
      key: col,
      header: EXPORT_COLUMN_LABELS[col],
      format: (value: unknown, row: ClientMetrics) => {
        switch (col) {
          case "trafficTrendPct":
            return `${((row.trafficTrendPct ?? 0) * 100).toFixed(1)}%`;
          case "lastReportAt":
          case "lastAuditAt":
            return (value as string) ?? "Never";
          default:
            return String(value ?? "");
        }
      },
    }));
  }, [selectedColumns]);

  const handleExport = async () => {
    if (selectedColumns.length === 0) return;

    setIsExporting(true);
    try {
      // Use provided data or fetch from API
      let exportData: ClientMetrics[];
      if (data) {
        exportData = data;
      } else {
        const params = new URLSearchParams({
          columns: selectedColumns.join(","),
        });

        const response = await fetch(`/api/dashboard/export?${params}&format=json`);
        if (!response.ok) throw new Error("Export failed");
        exportData = await response.json();
      }

      const columns = buildColumns();

      if (selectedFormat === "csv") {
        generateCSV(exportData, columns as CSVColumn<ClientMetrics>[], filename);
      } else {
        generatePDF(
          exportData,
          columns as PDFColumn<ClientMetrics>[],
          createPDFOptions(title, {
            subtitle: `${exportData.length} clients`,
            orientation: selectedColumns.length > 6 ? "landscape" : "portrait",
            footerText: "Generated by Tevero SEO Platform",
          })
        );
      }

      onOpenChange(false);
      onExportComplete?.();
    } catch (error) {
      // Error logged for debugging
      if (process.env.NODE_ENV === "development") {
        // eslint-disable-next-line no-console
        console.error("Export failed:", error);
      }
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {selectedFormat === "csv" ? (
              <FileSpreadsheet className="h-5 w-5" />
            ) : (
              <FileText className="h-5 w-5" />
            )}
            Export Data
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Format Selection */}
          <div className="space-y-2">
            <Label>Export Format</Label>
            <div className="flex gap-2">
              <Button
                type="button"
                variant={selectedFormat === "csv" ? "default" : "outline"}
                size="sm"
                onClick={() => handleFormatChange("csv")}
                className="flex-1"
              >
                <FileSpreadsheet className="mr-2 h-4 w-4" />
                CSV
              </Button>
              <Button
                type="button"
                variant={selectedFormat === "pdf" ? "default" : "outline"}
                size="sm"
                onClick={() => handleFormatChange("pdf")}
                className="flex-1"
              >
                <FileText className="mr-2 h-4 w-4" />
                PDF
              </Button>
            </div>
          </div>

          {/* Filename Input */}
          <div className="space-y-2">
            <Label htmlFor="export-filename">Filename</Label>
            <div className="flex items-center gap-2">
              <Input
                id="export-filename"
                value={filename}
                onChange={(e) => setFilename(e.target.value)}
                placeholder="Enter filename"
                className="flex-1"
              />
              <span className="text-sm text-muted-foreground">
                .{selectedFormat}
              </span>
            </div>
          </div>

          {/* Column Selection */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Columns to Export</Label>
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="link"
                  size="sm"
                  onClick={() => setSelectedColumns(ALL_COLUMNS)}
                  className="p-0 h-auto text-xs"
                >
                  Select All
                </Button>
                <span className="text-muted-foreground">|</span>
                <Button
                  type="button"
                  variant="link"
                  size="sm"
                  onClick={() => setSelectedColumns(DEFAULT_COLUMNS)}
                  className="p-0 h-auto text-xs"
                >
                  Reset
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto p-2 border rounded-md">
              {ALL_COLUMNS.map((column) => (
                <div key={column} className="flex items-center space-x-2">
                  <Checkbox
                    id={`dialog-col-${column}`}
                    checked={selectedColumns.includes(column)}
                    onCheckedChange={() => toggleColumn(column)}
                  />
                  <Label
                    htmlFor={`dialog-col-${column}`}
                    className="text-sm font-normal cursor-pointer"
                  >
                    {EXPORT_COLUMN_LABELS[column]}
                  </Label>
                </div>
              ))}
            </div>
            <p className="text-xs text-muted-foreground">
              {selectedColumns.length} of {ALL_COLUMNS.length} columns selected
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleExport}
            disabled={selectedColumns.length === 0 || isExporting || !filename.trim()}
          >
            {isExporting ? "Exporting..." : `Export ${selectedFormat.toUpperCase()}`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
