"use client";

import { useState, useCallback } from "react";
import {
  Button,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  Checkbox,
  Label,
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@tevero/ui";
import { Download, FileSpreadsheet, FileText, ChevronDown } from "lucide-react";
import type { ExportColumn, ClientMetrics } from "@/lib/dashboard/types";
import { EXPORT_COLUMN_LABELS } from "@/lib/dashboard/types";
import { generateCSV, type CSVColumn } from "@/lib/export/csv";
import { generatePDF, type PDFColumn, createPDFOptions } from "@/lib/export/pdf";

export type ExportFormat = "csv" | "pdf";

const ALL_COLUMNS: ExportColumn[] = [
  "clientName",
  "healthScore",
  "trafficCurrent",
  "trafficTrendPct",
  "keywordsTotal",
  "keywordsTop10",
  "keywordsTop3",
  "keywordsPosition1",
  "alertsOpen",
  "connectionStatus",
  "lastReportAt",
  "lastAuditAt",
];

const DEFAULT_COLUMNS: ExportColumn[] = [
  "clientName",
  "healthScore",
  "trafficCurrent",
  "trafficTrendPct",
  "keywordsTotal",
  "alertsOpen",
];

interface ExportButtonProps {
  /** Optional: pre-filtered data to export. If not provided, fetches from API. */
  data?: ClientMetrics[];
}

export function ExportButton({ data }: ExportButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [selectedColumns, setSelectedColumns] = useState<ExportColumn[]>(DEFAULT_COLUMNS);
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>("csv");
  const [isExporting, setIsExporting] = useState(false);

  const toggleColumn = (column: ExportColumn) => {
    setSelectedColumns((prev) =>
      prev.includes(column)
        ? prev.filter((c) => c !== column)
        : [...prev, column]
    );
  };

  const openExportDialog = (format: ExportFormat) => {
    setSelectedFormat(format);
    setDropdownOpen(false);
    setIsOpen(true);
  };

  const buildColumns = useCallback(() => {
    return selectedColumns.map((col) => ({
      key: col,
      header: EXPORT_COLUMN_LABELS[col],
      format: (value: unknown, row: ClientMetrics) => {
        switch (col) {
          case "trafficTrendPct":
            return `${((row.trafficTrendPct ?? 0) * 100).toFixed(1)}%`;
          case "lastReportAt":
          case "lastAuditAt":
            return (value as string) ?? "Never";
          default:
            return String(value ?? "");
        }
      },
    }));
  }, [selectedColumns]);

  const handleExport = async () => {
    if (selectedColumns.length === 0) return;

    setIsExporting(true);
    try {
      // Use provided data or fetch from API
      let exportData: ClientMetrics[];
      if (data) {
        exportData = data;
      } else {
        const params = new URLSearchParams({
          columns: selectedColumns.join(","),
        });

        const response = await fetch(`/api/dashboard/export?${params}&format=json`);
        if (!response.ok) throw new Error("Export failed");
        exportData = await response.json();
      }

      const columns = buildColumns();
      const filename = `clients-export-${new Date().toISOString().split("T")[0]}`;

      if (selectedFormat === "csv") {
        generateCSV(exportData, columns as CSVColumn<ClientMetrics>[], filename);
      } else {
        generatePDF(
          exportData,
          columns as PDFColumn<ClientMetrics>[],
          createPDFOptions("Client Portfolio Report", {
            subtitle: `${exportData.length} clients`,
            orientation: selectedColumns.length > 6 ? "landscape" : "portrait",
            footerText: "Generated by Tevero SEO Platform",
          })
        );
      }

      setIsOpen(false);
    } catch (error) {
      // Error logged for debugging; user sees disabled state cleared
      if (process.env.NODE_ENV === "development") {
        // eslint-disable-next-line no-console
        console.error("Export failed:", error);
      }
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <>
      <Popover open={dropdownOpen} onOpenChange={setDropdownOpen}>
        <PopoverTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Export
            <ChevronDown className="h-3 w-3 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-40 p-1" align="end">
          <button
            onClick={() => openExportDialog("csv")}
            className="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground"
          >
            <FileSpreadsheet className="h-4 w-4" />
            Export as CSV
          </button>
          <button
            onClick={() => openExportDialog("pdf")}
            className="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground"
          >
            <FileText className="h-4 w-4" />
            Export as PDF
          </button>
        </PopoverContent>
      </Popover>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogTrigger asChild>
          <span className="sr-only">Open export dialog</span>
        </DialogTrigger>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              {selectedFormat === "csv" ? (
                <FileSpreadsheet className="h-5 w-5" />
              ) : (
                <FileText className="h-5 w-5" />
              )}
              Export to {selectedFormat.toUpperCase()}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 pt-4">
            <div className="space-y-2">
              <Label>Select columns to export:</Label>
              <div className="grid grid-cols-2 gap-2">
                {ALL_COLUMNS.map((column) => (
                  <div key={column} className="flex items-center space-x-2">
                    <Checkbox
                      id={`export-col-${column}`}
                      checked={selectedColumns.includes(column)}
                      onCheckedChange={() => toggleColumn(column)}
                    />
                    <Label htmlFor={`export-col-${column}`} className="text-sm font-normal cursor-pointer">
                      {EXPORT_COLUMN_LABELS[column]}
                    </Label>
                  </div>
                ))}
              </div>
            </div>
            <div className="flex items-center justify-between">
              <Button
                variant="link"
                size="sm"
                onClick={() => setSelectedColumns(ALL_COLUMNS)}
                className="p-0 h-auto"
              >
                Select All
              </Button>
              <Button
                variant="link"
                size="sm"
                onClick={() => setSelectedColumns(DEFAULT_COLUMNS)}
                className="p-0 h-auto"
              >
                Reset to Default
              </Button>
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setIsOpen(false)}>
                Cancel
              </Button>
              <Button
                onClick={handleExport}
                disabled={selectedColumns.length === 0 || isExporting}
              >
                {isExporting ? "Exporting..." : `Download ${selectedFormat.toUpperCase()}`}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
