/**
 * Content Intelligence Schema
 * Phase 96-04: Content Groups, Topic Clusters, Index Coverage
 *
 * Design decisions:
 * - content_groups: folder-based, regex, and manual grouping types
 * - topic_clusters: hub + spoke relationship with coverage tracking
 * - page_index_status: URL Inspection API results with all Google fields
 * - indexing_requests: Track batch indexing with status and response
 */
import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  jsonb,
  integer,
  real,
  index,
  unique,
} from "drizzle-orm/pg-core";
import { siteConnections } from "./connection-schema";
import { organization } from "./user-schema";

// ===== Content Groups =====

export const contentGroups = pgTable(
  "content_groups",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: text("site_id")
      .notNull()
      .references(() => siteConnections.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    matchType: text("match_type").notNull(), // 'folder', 'regex', 'manual'
    matchPattern: text("match_pattern"), // e.g., '/blog/' or '^/products/.*'
    color: text("color"), // Hex color for UI
    isAutoGenerated: boolean("is_auto_generated").default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("uq_content_groups_site_name").on(table.siteId, table.name),
    index("idx_content_groups_site").on(table.siteId),
    index("idx_content_groups_soft_deleted").on(table.softDeletedAt),
  ]
);

export const contentGroupPages = pgTable(
  "content_group_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => contentGroups.id, { onDelete: "cascade" }),
    pageUrl: text("page_url").notNull(),
    manuallyAdded: boolean("manually_added").default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    unique("uq_content_group_pages").on(table.groupId, table.pageUrl),
    index("idx_content_group_pages_group").on(table.groupId),
    index("idx_content_group_pages_url").on(table.pageUrl),
  ]
);

// ===== Analytics Topic Clusters (Hub + Spoke) =====
// Note: Prefixed with 'analytics' to distinguish from onpage-mastery-schema topicClusters

export const analyticsTopicClusters = pgTable(
  "analytics_topic_clusters",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: text("site_id")
      .notNull()
      .references(() => siteConnections.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    hubPageUrl: text("hub_page_url").notNull(),
    hubTopic: text("hub_topic").notNull(),
    coverage: real("coverage").default(0), // 0-100 percentage
    totalClicks: integer("total_clicks").default(0),
    totalImpressions: integer("total_impressions").default(0),
    avgPosition: real("avg_position"),
    gaps: jsonb("gaps").$type<string[]>().default([]), // Missing subtopics
    lastAnalyzedAt: timestamp("last_analyzed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("uq_analytics_topic_clusters_site_hub").on(table.siteId, table.hubPageUrl),
    index("idx_analytics_topic_clusters_site").on(table.siteId),
    index("idx_analytics_topic_clusters_soft_deleted").on(table.softDeletedAt),
  ]
);

export const analyticsTopicClusterPages = pgTable(
  "analytics_topic_cluster_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clusterId: uuid("cluster_id")
      .notNull()
      .references(() => analyticsTopicClusters.id, { onDelete: "cascade" }),
    pageUrl: text("page_url").notNull(),
    pageTopic: text("page_topic"),
    isHub: boolean("is_hub").default(false),
    linksToHub: boolean("links_to_hub").default(false),
    internalLinkCount: integer("internal_link_count").default(0),
    clicks: integer("clicks").default(0),
    impressions: integer("impressions").default(0),
    position: real("position"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    unique("uq_analytics_topic_cluster_pages").on(table.clusterId, table.pageUrl),
    index("idx_analytics_topic_cluster_pages_cluster").on(table.clusterId),
    index("idx_analytics_topic_cluster_pages_url").on(table.pageUrl),
  ]
);

// ===== Index Coverage =====

export const pageIndexStatus = pgTable(
  "page_index_status",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: text("site_id")
      .notNull()
      .references(() => siteConnections.id, { onDelete: "cascade" }),
    pageUrl: text("page_url").notNull(),
    // Coverage states from GSC URL Inspection API
    coverageState: text("coverage_state"), // 'Submitted and indexed', 'Crawled - currently not indexed', 'Discovered - currently not indexed', 'URL is unknown to Google', 'Page with redirect', 'Not found (404)', 'Blocked by robots.txt', 'Blocked by noindex', etc.
    indexingState: text("indexing_state"), // 'Indexed', 'Not indexed'
    lastCrawlTime: timestamp("last_crawl_time", { withTimezone: true }),
    crawledAs: text("crawled_as"), // 'Googlebot Desktop', 'Googlebot Smartphone'
    robotsTxtState: text("robots_txt_state"), // 'ALLOWED', 'DISALLOWED', 'UNKNOWN'
    canonicalUrl: text("canonical_url"),
    isCanonical: boolean("is_canonical"),
    mobileUsability: text("mobile_usability"), // 'MOBILE_FRIENDLY', 'NOT_MOBILE_FRIENDLY', 'MOBILE_USABILITY_UNSPECIFIED'
    richResults: jsonb("rich_results").$type<{
      detected: string[];
      items?: unknown[];
    }>(),
    // Additional inspection metadata
    userDeclaredCanonical: text("user_declared_canonical"),
    googleSelectedCanonical: text("google_selected_canonical"),
    pageFetchState: text("page_fetch_state"), // 'SUCCESSFUL', 'SOFT_404', 'BLOCKED_ROBOTS_TXT', 'NOT_FOUND', 'ACCESS_DENIED', 'SERVER_ERROR', 'REDIRECT_ERROR', 'ACCESS_FORBIDDEN', 'BLOCKED_4XX', 'INTERNAL_CRAWL_ERROR', 'INVALID_URL'
    referringUrls: jsonb("referring_urls").$type<string[]>(),
    // Timestamps
    inspectionTime: timestamp("inspection_time", {
      withTimezone: true,
    }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("uq_page_index_status").on(table.siteId, table.pageUrl),
    index("idx_page_index_coverage_state").on(table.siteId, table.coverageState),
    index("idx_page_index_indexing_state").on(table.siteId, table.indexingState),
    index("idx_page_index_crawl_time").on(table.siteId, table.lastCrawlTime),
    index("idx_page_index_soft_deleted").on(table.softDeletedAt),
  ]
);

export const indexingRequests = pgTable(
  "indexing_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: text("site_id")
      .notNull()
      .references(() => siteConnections.id, { onDelete: "cascade" }),
    pageUrl: text("page_url").notNull(),
    requestType: text("request_type").notNull(), // 'URL_UPDATED', 'URL_DELETED'
    status: text("status").notNull().default("pending"), // 'pending', 'submitted', 'success', 'failed', 'quota_exceeded'
    priority: integer("priority").default(0), // Higher = more urgent
    priorityReason: text("priority_reason"), // 'new_content', 'decaying', 'high_value', 'manual'
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    response: jsonb("response").$type<{
      notificationType?: string;
      urlNotificationMetadata?: unknown;
      error?: string;
    }>(),
    errorMessage: text("error_message"),
    retryCount: integer("retry_count").default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
  },
  (table) => [
    index("idx_indexing_requests_site_status").on(table.siteId, table.status),
    index("idx_indexing_requests_priority").on(table.priority),
    index("idx_indexing_requests_submitted").on(table.submittedAt),
    index("idx_indexing_requests_soft_deleted").on(table.softDeletedAt),
  ]
);

// ===== Annotations =====
// Phase 96-03: Timeline annotations for analytics charts

export const annotations = pgTable(
  "analytics_annotations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    siteId: text("site_id").references(() => siteConnections.id, {
      onDelete: "cascade",
    }), // null = workspace-wide annotation
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    annotationDate: text("annotation_date").notNull(), // YYYY-MM-DD format
    annotationType: text("annotation_type").notNull(), // 'algorithm_update', 'site_change', 'marketing_campaign', 'technical_issue', 'other'
    title: text("title").notNull(),
    description: text("description"),
    category: text("category"), // 'algorithm_update', 'site_change', 'marketing_campaign', 'technical_issue', 'other'
    color: text("color"), // Hex color for chart display (e.g., "#FF5733")
    impact: text("impact"), // 'positive', 'negative', 'neutral', 'unknown'
    autoGenerated: boolean("auto_generated").default(false),
    sourceUrl: text("source_url"),
    createdBy: text("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("uq_annotations_workspace_date_title").on(
      table.workspaceId,
      table.annotationDate,
      table.title
    ),
    index("idx_annotations_workspace").on(table.workspaceId),
    index("idx_annotations_site").on(table.siteId),
    index("idx_annotations_date").on(table.annotationDate),
    index("idx_annotations_type").on(table.annotationType),
    index("idx_annotations_soft_deleted").on(table.softDeletedAt),
  ]
);

// ===== Google Algorithm Updates =====
// Phase 96: Auto-imported from DemandSphere API for correlation with traffic changes

export const googleAlgorithmUpdates = pgTable(
  "google_algorithm_updates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(), // e.g., "March 2024 Core Update"
    updateType: text("update_type").notNull(), // 'core', 'spam', 'helpful_content', 'product_reviews', 'link_spam'
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }), // null if still rolling
    severity: text("severity").notNull(), // 'major', 'minor', 'refresh'
    officialAnnouncementUrl: text("official_announcement_url"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index("idx_algorithm_updates_started_at").on(table.startedAt),
    index("idx_algorithm_updates_type").on(table.updateType),
    index("idx_algorithm_updates_severity").on(table.severity),
  ]
);

// Type exports for type-safe queries
export type Annotation = typeof annotations.$inferSelect;
export type AnnotationInsert = typeof annotations.$inferInsert;
export type ContentGroup = typeof contentGroups.$inferSelect;
export type ContentGroupInsert = typeof contentGroups.$inferInsert;
export type ContentGroupPage = typeof contentGroupPages.$inferSelect;
export type ContentGroupPageInsert = typeof contentGroupPages.$inferInsert;
export type AnalyticsTopicCluster = typeof analyticsTopicClusters.$inferSelect;
export type AnalyticsTopicClusterInsert = typeof analyticsTopicClusters.$inferInsert;
export type AnalyticsTopicClusterPage = typeof analyticsTopicClusterPages.$inferSelect;
export type AnalyticsTopicClusterPageInsert = typeof analyticsTopicClusterPages.$inferInsert;
export type PageIndexStatus = typeof pageIndexStatus.$inferSelect;
export type PageIndexStatusInsert = typeof pageIndexStatus.$inferInsert;
export type IndexingRequest = typeof indexingRequests.$inferSelect;
export type IndexingRequestInsert = typeof indexingRequests.$inferInsert;
export type GoogleAlgorithmUpdate = typeof googleAlgorithmUpdates.$inferSelect;
export type GoogleAlgorithmUpdateInsert = typeof googleAlgorithmUpdates.$inferInsert;
