-- Migration: 0067_schema_consistency_fixes.sql
-- Date: 2026-05-03
-- Agent: 2 (Database Schema Consistency)
-- Purpose: Fix CRITICAL, HIGH, and MEDIUM database schema issues
--
-- Issues Addressed:
--   CRITICAL-01: Document client sync relationship (AI-Writer authoritative)
--   HIGH-01: UUID type already standardized in 0034 - verify consistency
--   HIGH-02: Add FK to client_settings.client_id (AI-Writer side)
--   HIGH-03: Align voice_profiles FK behavior to SET NULL (migration 0038 already did this)
--   HIGH-04: user_id columns already use TEXT for Clerk compatibility
--   MEDIUM-01: Document timestamp mechanism differences
--   MEDIUM-02: Standardize soft delete pattern (deleted_at timestamp)
--   MEDIUM-03: Add missing FK indexes
--   MEDIUM-04: Remove deprecated column aliases (analytics-schema.ts)
--
-- Note: AI-Writer changes require separate SQLAlchemy migrations
-- This migration focuses on open-seo-main (Drizzle) side

BEGIN;

-- ============================================================================
-- CRITICAL-01: Document Client Sync Relationship
-- AI-Writer's clients table is authoritative. Add documentation.
-- ============================================================================

COMMENT ON TABLE clients IS
  'Client records for open-seo-main SEO platform. '
  'SYNC RELATIONSHIP: AI-Writer maintains the authoritative clients table. '
  'Changes to client name/domain should be synced via webhook from AI-Writer. '
  'This table may contain additional SEO-specific fields not in AI-Writer. '
  'Primary key (id) is UUID format, shared between both systems.';

COMMENT ON COLUMN clients.id IS
  'UUID primary key. MUST match AI-Writer clients.id for cross-system queries. '
  'Generated by AI-Writer when client is created.';

COMMENT ON COLUMN clients.workspace_id IS
  'Clerk organization ID for multi-tenant isolation. '
  'Synced from AI-Writer workspace_id.';


-- ============================================================================
-- HIGH-01: Verify UUID Type Consistency (Migration 0034 already converted)
-- This section validates existing UUID columns are correct
-- ============================================================================

DO $$
DECLARE
  mismatch_count INTEGER := 0;
  col_record RECORD;
BEGIN
  -- Check all client_id columns are UUID type
  FOR col_record IN
    SELECT table_name, column_name, udt_name
    FROM information_schema.columns
    WHERE column_name = 'client_id'
      AND table_schema = 'public'
      AND udt_name != 'uuid'
  LOOP
    RAISE NOTICE 'MISMATCH: %.% is % (expected uuid)',
      col_record.table_name, col_record.column_name, col_record.udt_name;
    mismatch_count := mismatch_count + 1;
  END LOOP;

  IF mismatch_count > 0 THEN
    RAISE WARNING 'Found % columns with non-UUID client_id. Review and fix manually.', mismatch_count;
  ELSE
    RAISE NOTICE 'UUID consistency check passed: all client_id columns are UUID type.';
  END IF;
END $$;


-- ============================================================================
-- HIGH-03: Verify voice_profiles FK uses SET NULL (Already done in 0038)
-- This section validates the FK behavior is correct
-- ============================================================================

DO $$
DECLARE
  delete_action TEXT;
BEGIN
  SELECT confdeltype INTO delete_action
  FROM pg_constraint pc
  JOIN pg_class c ON pc.conrelid = c.oid
  WHERE c.relname = 'voice_profiles'
    AND pc.conname LIKE '%client_id%';

  IF delete_action IS NULL THEN
    RAISE NOTICE 'voice_profiles FK constraint not found - may need to verify schema.';
  ELSIF delete_action = 'n' THEN -- 'n' = SET NULL
    RAISE NOTICE 'voice_profiles.client_id FK correctly uses SET NULL.';
  ELSIF delete_action = 'c' THEN -- 'c' = CASCADE
    RAISE WARNING 'voice_profiles.client_id FK uses CASCADE - should be SET NULL. Fix in separate migration.';
  ELSE
    RAISE NOTICE 'voice_profiles.client_id FK action: %', delete_action;
  END IF;
END $$;


-- ============================================================================
-- MEDIUM-01: Document Timestamp Mechanism Differences
-- ============================================================================

COMMENT ON SCHEMA public IS
  'TeveroSEO database (open-seo-main). '
  'TIMESTAMP NOTES: '
  '  - Drizzle ORM uses defaultNow() for created_at/updated_at '
  '  - AI-Writer (SQLAlchemy) uses func.now() and onupdate=func.now() '
  '  - Both generate equivalent PostgreSQL: DEFAULT now() '
  '  - Client applications see identical behavior '
  '  - For Drizzle, $onUpdate() is application-level (requires ORM update call) '
  '  - For explicit DB-level updates, use TRIGGER (see migration 0070 if needed)';


-- ============================================================================
-- MEDIUM-02: Soft Delete Pattern Standardization
-- Ensure all soft-deletable tables use consistent pattern:
--   is_deleted BOOLEAN NOT NULL DEFAULT FALSE
--   deleted_at TIMESTAMPTZ (nullable)
-- Tables already conforming: clients, projects, audits, site_changes,
--   voice_profiles, seo_gsc_snapshots, seo_ga4_snapshots, gsc_query_snapshots
-- ============================================================================

-- Add soft delete to content_briefs if not present
ALTER TABLE content_briefs
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE content_briefs
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ix_content_briefs_deleted ON content_briefs (is_deleted);

-- Add soft delete to proposals if not present
ALTER TABLE proposals
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE proposals
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ix_proposals_deleted ON proposals (is_deleted);

-- Add soft delete to reports if not present
ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ix_reports_deleted ON reports (is_deleted);


-- ============================================================================
-- MEDIUM-03: Add Missing FK Indexes
-- Foreign key columns should have indexes for efficient JOIN/DELETE operations
-- ============================================================================

-- prospect_keywords.prospect_id
CREATE INDEX IF NOT EXISTS ix_prospect_keywords_prospect_id ON prospect_keywords (prospect_id);

-- proposal_services.proposal_id
CREATE INDEX IF NOT EXISTS ix_proposal_services_proposal_id ON proposal_services (proposal_id);

-- invoices.contract_id (if table exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'invoices') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_invoices_contract_id ON invoices (contract_id)';
  END IF;
END $$;

-- invoice_items.invoice_id (if table exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'invoice_items') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_invoice_items_invoice_id ON invoice_items (invoice_id)';
  END IF;
END $$;

-- tasks.client_id (if table exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tasks') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_tasks_client_id ON tasks (client_id)';
  END IF;
END $$;

-- follow_ups.prospect_id (if table exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'follow_ups') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_follow_ups_prospect_id ON follow_ups (prospect_id)';
  END IF;
END $$;

-- magic_links.organization_id (if table exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'magic_links') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS ix_magic_links_organization_id ON magic_links (organization_id)';
  END IF;
END $$;


-- ============================================================================
-- Document Soft Delete Helper Pattern
-- ============================================================================

COMMENT ON COLUMN clients.is_deleted IS
  'Soft delete flag. TRUE = logically deleted, FALSE = active. '
  'Use WHERE is_deleted = FALSE in all queries unless explicitly including deleted records. '
  'Helper: See withSoftDelete() query modifier in src/server/lib/soft-delete.ts';


COMMIT;

-- ============================================================================
-- ROLLBACK SCRIPT (run manually if needed)
-- ============================================================================
-- BEGIN;
-- DROP INDEX IF EXISTS ix_magic_links_organization_id;
-- DROP INDEX IF EXISTS ix_follow_ups_prospect_id;
-- DROP INDEX IF EXISTS ix_tasks_client_id;
-- DROP INDEX IF EXISTS ix_invoice_items_invoice_id;
-- DROP INDEX IF EXISTS ix_invoices_contract_id;
-- DROP INDEX IF EXISTS ix_proposal_services_proposal_id;
-- DROP INDEX IF EXISTS ix_prospect_keywords_prospect_id;
-- DROP INDEX IF EXISTS ix_reports_deleted;
-- ALTER TABLE reports DROP COLUMN IF EXISTS deleted_at;
-- ALTER TABLE reports DROP COLUMN IF EXISTS is_deleted;
-- DROP INDEX IF EXISTS ix_proposals_deleted;
-- ALTER TABLE proposals DROP COLUMN IF EXISTS deleted_at;
-- ALTER TABLE proposals DROP COLUMN IF EXISTS is_deleted;
-- DROP INDEX IF EXISTS ix_content_briefs_deleted;
-- ALTER TABLE content_briefs DROP COLUMN IF EXISTS deleted_at;
-- ALTER TABLE content_briefs DROP COLUMN IF EXISTS is_deleted;
-- COMMIT;
