/**
 * Analytics Feature Types
 * Phase 96-01: GSC Analytics Infrastructure
 * Phase 96-API: Standardized API Response Types
 */

// Re-export API response types
export * from './types/api-responses';

export interface GscQueryRow {
  query: string;
  pageUrl?: string;
  country?: string;
  device?: string;
  searchAppearance?: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface PaginationOptions {
  siteId: string;
  siteUrl: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  dimensions: string[];
  rowLimit?: number; // default 25000
}

export type DimensionCombination =
  | ["query"]
  | ["query", "page"]
  | ["query", "country"]
  | ["page"];

export const DIMENSION_COMBINATIONS: DimensionCombination[] = [
  ["query"],
  ["query", "page"],
  ["query", "country"],
  ["page"],
];

/**
 * Phase 96-02: Master Dashboard Types
 * Re-export common types from @tevero/types for backward compatibility.
 */

// Import from unified types package
import type { DateRange, ComparisonPeriod } from "@tevero/types/common";

// Re-export for backward compatibility
export type { DateRange, ComparisonPeriod };

export interface DashboardFilters {
  dateRange: DateRange;
  comparison?: ComparisonPeriod;
  tags?: string[];
  siteIds?: string[];
}

export interface SiteMetrics {
  siteId: string;
  siteName: string;
  siteUrl: string;
  tags: string[];
  metrics: {
    clicks: number;
    impressions: number;
    ctr: number;
    position: number;
  };
  comparison: {
    clicksChange: number;      // Percentage change from comparison period
    impressionsChange: number;
    ctrChange: number;
    positionChange: number;    // Negative = improvement (lower position is better)
  };
  trend: Array<{ date: string; clicks: number }>;  // 7-day sparkline
}

export interface DashboardAggregates {
  totals: {
    clicks: number;
    impressions: number;
    avgPosition: number;
    avgCtr: number;
  };
  comparison: {
    clicksChange: number;
    impressionsChange: number;
    positionChange: number;
    ctrChange: number;
  };
  sites: SiteMetrics[];
  meta: {
    siteCount: number;
    dateRange: DateRange;
    comparisonPeriod: DateRange | null;
  };
}

/**
 * Phase 96-03: Trend Detection Types
 */

export interface TrendAnalysis {
  pageUrl: string;
  pageTitle?: string;
  currentClicks: number;
  previousClicks: number;
  currentImpressions: number;
  previousImpressions: number;
  currentPosition: number;
  previousPosition: number;
  changePercent: number;
  trend: 'growing' | 'decaying' | 'stable';
  confidence: 'high' | 'medium' | 'low';
  topQueries: string[];
}

export interface QueryFilter {
  include?: string[];   // AND terms
  exclude?: string[];   // NOT terms
  pattern?: string;     // Regex pattern
  mode?: 'and' | 'or';  // Combine include terms with AND or OR
}

export interface TrendFilters {
  periodDays?: number;      // default 21 (3 weeks)
  threshold?: number;       // default 0.10 (10%)
  minImpressions?: number;  // default 100
  trend?: 'growing' | 'decaying' | 'all';
  queryFilter?: QueryFilter;
}

export interface TrendResult {
  pages: TrendAnalysis[];
  meta: {
    totalAnalyzed: number;
    growingCount: number;
    decayingCount: number;
    stableCount: number;
    periodDays: number;
    threshold: number;
  };
}

/**
 * Phase 96-03: Striking Distance Types
 */

export interface StrikingDistancePage {
  pageUrl: string;
  pageTitle?: string;
  avgPosition: number;
  impressions: number;
  currentClicks: number;
  potentialClicks: number;   // Estimated clicks if moved to position 1-3
  clickGain: number;         // potentialClicks - currentClicks
  difficulty: 'easy' | 'medium' | 'hard';
  topQueries: Array<{
    query: string;
    position: number;
    impressions: number;
    clicks: number;
  }>;
}

export interface StrikingDistanceFilters {
  minPosition?: number;      // default 11
  maxPosition?: number;      // default 20
  minImpressions?: number;   // default 50
  targetPosition?: number;   // default 3 (estimate CTR at this position)
  limit?: number;            // default 100
}

export interface StrikingDistanceResult {
  pages: StrikingDistancePage[];
  meta: {
    totalPages: number;
    totalPotentialClicks: number;
    avgDifficulty: number;  // 1=easy, 2=medium, 3=hard
  };
}

/**
 * Phase 96-03: Annotation Types
 */

export type AnnotationType = 'core_update' | 'spam_update' | 'helpful_content' | 'product_reviews' | 'link_spam' | 'site_change' | 'custom';
export type AnnotationImpact = 'positive' | 'negative' | 'neutral' | 'unknown';

export interface Annotation {
  id: string;
  siteId: string | null;  // null = global (Google updates)
  workspaceId: string;
  annotationDate: Date;
  annotationType: AnnotationType;
  title: string;
  description?: string;
  impact: AnnotationImpact;
  autoGenerated: boolean;
  sourceUrl?: string;
  createdBy?: string;
  createdAt: Date;
}

export interface GoogleAlgorithmUpdate {
  date: string;
  name: string;
  description?: string;
  type: string;
  confirmed: boolean;
  source_url?: string;
}

export interface AnnotationFilters {
  siteId?: string;
  startDate?: string;
  endDate?: string;
  types?: AnnotationType[];
  includeGlobal?: boolean;  // Include site_id=null annotations
}

/**
 * Phase 96-04: Content Group types
 */

export interface ContentGroupWithMetrics {
  id: string;
  siteId: string;
  name: string;
  description: string | null;
  matchType: 'folder' | 'regex' | 'manual';
  matchPattern: string | null;
  color: string | null;
  isAutoGenerated: boolean | null;
  pageCount: number;
  metrics: {
    totalClicks: number;
    totalImpressions: number;
    avgPosition: number;
    clicksChange: number;  // vs previous period percentage
    impressionsChange: number;
  };
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface ContentGroupCreateInput {
  name: string;
  description?: string;
  matchType: 'folder' | 'regex' | 'manual';
  matchPattern?: string;
  color?: string;
}

export interface ContentGroupUpdateInput {
  name?: string;
  description?: string;
  matchPattern?: string;
  color?: string;
}

export interface AutoGroupResult {
  created: ContentGroupWithMetrics[];
  skipped: Array<{ folder: string; reason: string; pageCount: number }>;
}

/**
 * Phase 96-04: Topic Cluster types
 */

export interface TopicClusterWithPages {
  id: string;
  siteId: string;
  name: string;
  hubPage: {
    url: string;
    topic: string;
    title?: string;
    clicks: number;
    impressions: number;
    position: number;
    internalLinks: number;
  };
  spokePages: Array<{
    url: string;
    topic: string | null;
    title?: string;
    linksToHub: boolean;
    internalLinkCount: number;
    clicks: number;
    impressions: number;
    position: number | null;
  }>;
  coverage: number;  // 0-100%
  gaps: string[];    // Missing subtopics
  totalClicks: number;
  totalImpressions: number;
  avgPosition: number;
  lastAnalyzedAt: Date | null;
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface ClusterDetectionOptions {
  minHubLinks?: number;     // Minimum incoming links to be a hub (default: 10)
  minSpokeLinks?: number;   // Minimum links from spoke to hub (default: 1)
  maxSpokesPerHub?: number; // Max spokes to include (default: 50)
}

export interface ClusterCreateInput {
  name: string;
  hubPageUrl: string;
  hubTopic: string;
}

export interface ClusterGapAnalysis {
  clusterId: string;
  clusterName: string;
  coverage: number;
  gaps: string[];
  recommendations: Array<{
    subtopic: string;
    searchVolume?: number;
    difficulty?: number;
    suggestedTitle: string;
  }>;
}

/**
 * Phase 96-04: Index Coverage types
 */

export interface UrlInspectionResult {
  pageUrl: string;
  inspectionTime: Date;
  coverageState: string;
  indexingState: string;
  lastCrawlTime: Date | null;
  crawledAs: string | null;
  robotsTxtState: string | null;
  canonicalUrl: string | null;
  isCanonical: boolean | null;
  mobileUsability: string | null;
  richResults: { detected: string[]; items?: unknown[] } | null;
  pageFetchState: string | null;
  referringUrls: string[] | null;
  userDeclaredCanonical: string | null;
  googleSelectedCanonical: string | null;
}

export interface InspectionPriority {
  pageUrl: string;
  priority: number;
  reason: 'new_content' | 'decaying' | 'high_value' | 'stale' | 'manual';
  createdAt: Date;
}

export interface IndexCoverageStats {
  total: number;
  indexed: number;
  notIndexed: number;
  byState: Record<string, number>;
  lastUpdated: Date;
}

export interface BatchIndexingRequest {
  siteId: string;
  urls: string[];
  requestType: 'URL_UPDATED' | 'URL_DELETED';
  priority: number;
}

export interface IndexingQuota {
  inspectionsUsed: number;
  inspectionsLimit: number;
  indexingRequestsUsed: number;
  indexingRequestsLimit: number;
  resetsAt: Date;
}

/**
 * Phase 96-05: Client Portal Types
 */

export interface VisibilityConfig {
  showClicks: boolean;
  showImpressions: boolean;
  showPosition: boolean;
  showCtr: boolean;
  showQueries: boolean;
  showPages: boolean;
  showCompetitors: boolean;
  canViewGrowing: boolean;
  canViewDecaying: boolean;
  canViewCannibalization: boolean;
  canExport: boolean;
}

export const DEFAULT_VISIBILITY: VisibilityConfig = {
  showClicks: true,
  showImpressions: true,
  showPosition: true,
  showCtr: true,
  showQueries: false,
  showPages: true,
  showCompetitors: false,
  canViewGrowing: true,
  canViewDecaying: true,
  canViewCannibalization: false,
  canExport: false,
};

export interface BrandTerm {
  id: string;
  clientId: string;
  term: string;
  isAutoDetected: boolean;
  createdAt: Date;
}

export interface BrandedSplit<T> {
  branded: T;
  nonBranded: T;
  brandedPercent: number;
  nonBrandedPercent: number;
}

export interface CtrComparison {
  position: number;
  benchmarkCtr: number;
  actualCtr: number;
  delta: number;
  deltaPercent: number;
  status: 'above' | 'at' | 'below';
}

export interface PortfolioSummary {
  totalClicks: number;
  totalImpressions: number;
  avgPosition: number;
  avgCtr: number;
  clientCount: number;
  totalQueries: number;
  totalPages: number;
}

export interface PortfolioTrend {
  date: string;
  clicks: number;
  impressions: number;
  avgPosition: number;
}

export interface ClientPerformance {
  clientId: string;
  clientName: string;
  domain: string;
  clicks: number;
  impressions: number;
  position: number;
  changePercent: number;
}

export interface ReportSchedule {
  id: string;
  workspaceId: string;
  clientId: string | null;
  frequency: 'weekly' | 'monthly';
  recipients: string[];
  nextRunAt: Date;
  lastRunAt: Date | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ExportColumn {
  key: string;
  header: string;
  format?: 'number' | 'percent' | 'currency' | 'date';
}
