/**
 * Report types for the apps/web report components.
 *
 * Re-exports core types from @tevero/types and adds
 * local types for report rendering (data payloads, labels).
 */

import type {
  GSCDataPoint,
  GA4DataPoint,
  TopQuery,
  GSCSummary,
  GA4Summary,
} from "@/lib/analytics/types";

// Re-export core report types from shared package
export type {
  ReportTemplate,
  ReportSection,
  ReportSectionType,
  ReportMetadata,
} from "@tevero/types";

/**
 * Full report data payload for rendering.
 * Contains all analytics data needed to render a complete report.
 */
export interface ReportData {
  /** Report metadata (id, client, date range, etc.) */
  metadata: import("@tevero/types").ReportMetadata;
  /** Daily GSC data points for chart */
  gscDaily: GSCDataPoint[];
  /** Aggregated GSC summary for stat cards */
  gscSummary: GSCSummary;
  /** Daily GA4 data points for chart */
  ga4Daily: GA4DataPoint[];
  /** Aggregated GA4 summary for stat cards */
  ga4Summary: GA4Summary;
  /** Top performing queries for table */
  topQueries: TopQuery[];
}

/**
 * Localized labels passed to report components.
 * All user-facing text should come from this interface
 * to support multi-language reports.
 */
export interface ReportLabels {
  /** Main report title */
  title: string;
  /** Report subtitle/description */
  subtitle: string;
  /** Date range label */
  dateRange: string;
  /** Clicks metric label */
  clicks: string;
  /** Impressions metric label */
  impressions: string;
  /** CTR metric label */
  ctr: string;
  /** Position metric label */
  position: string;
  /** Sessions metric label */
  sessions: string;
  /** Users metric label */
  users: string;
  /** Conversions metric label */
  conversions: string;
  /** Bounce rate metric label */
  bounceRate: string;
  /** Top queries section title */
  topQueries: string;
  /** Query column header */
  query: string;
  /** Week-over-week label */
  wow: string;
  /** Generated by attribution */
  generatedBy: string;
  /** Generated at timestamp label */
  generatedAt: string;
}

/**
 * Default English labels for reports.
 * Use as fallback or when locale is "en".
 */
export const DEFAULT_REPORT_LABELS: ReportLabels = {
  title: "Monthly SEO Report",
  subtitle: "Performance Overview",
  dateRange: "Date Range",
  clicks: "Clicks",
  impressions: "Impressions",
  ctr: "CTR",
  position: "Avg. Position",
  sessions: "Sessions",
  users: "Users",
  conversions: "Conversions",
  bounceRate: "Bounce Rate",
  topQueries: "Top Queries",
  query: "Query",
  wow: "vs. prev. period",
  generatedBy: "Generated by Tevero",
  generatedAt: "Generated at",
};
